// Generated by opengeodeweb-microservice-generate, do not edit.
import type json from "./opengeodeweb_front_schemas.json";

export interface CloudExtensionsRunParams {
  projectFolderPath: string;
  projectName: string;
}

export interface CloudExtensionsRunResponse {
  extensionsArray: CloudExtensionsRunResponseExtensionsArray[];
  statusCode: number;
}

export interface CloudExtensionsRunResponseExtensionsArray {
  frontendContent: string;
  id: string;
  name: string;
  port: number;
  version: string;
}

export interface LocalAppRunViewerParams {
  args: LocalAppRunViewerParamsArgs;
  COMMAND_VIEWER: string;
  NUXT_ROOT_PATH: string;
  [property: string]: any;
}

export interface LocalAppRunViewerParamsArgs {
  projectFolderPath: string;
  [property: string]: any;
}

export interface LocalAppRunViewerResponse {
  port: number;
  statusCode: number;
}

export interface LocalAppRunBackParams {
  args: LocalAppRunBackParamsArgs;
  COMMAND_BACK: string;
  NUXT_ROOT_PATH: string;
  [property: string]: any;
}

export interface LocalAppRunBackParamsArgs {
  projectFolderPath: string;
  [property: string]: any;
}

export interface LocalAppRunBackResponse {
  port: number;
  statusCode: number;
}

export interface LocalAppProjectFolderPathParams {
  PROJECT: string;
  [property: string]: any;
}

export interface LocalAppProjectFolderPathResponse {
  projectFolderPath: string;
  statusCode: number;
}

export interface LocalAppKillParams {}

export interface LocalAppKillResponse {}

export interface LocalExtensionsUploadParams {
  filename?: string;
}

export interface LocalExtensionsUploadResponse {
  statusCode: number;
}

export interface LocalExtensionsRunParams {
  projectFolderPath: string;
  projectName: string;
}

export interface LocalExtensionsRunResponse {
  extensionsArray: LocalExtensionsRunResponseExtensionsArray[];
  statusCode: number;
}

export interface LocalExtensionsRunResponseExtensionsArray {
  frontendContent: string;
  id: string;
  name: string;
  port: number;
  version: string;
}

export interface LocalExtensionsKillParams {
  extensionId: string;
  projectFolderPath: string;
  projectName: string;
}

export interface LocalExtensionsKillResponse {
  statusCode: number;
}

export interface MicroserviceAppSetViewerBaseURLParams {
  baseUrl: string;
}

export interface MicroserviceAppSetViewerBaseURLResponse {
  baseUrl: string;
  statusCode: number;
}

export interface MicroserviceAppSetIsAppReadyParams {
  isReady: boolean;
}

export interface MicroserviceAppSetIsAppReadyResponse {
  isReady: boolean;
  statusCode: number;
}

export interface MicroserviceAppSetBackBaseURLParams {
  baseUrl: string;
}

export interface MicroserviceAppSetBackBaseURLResponse {
  baseUrl: string;
  statusCode: number;
}

export interface MicroserviceAppSetAppBaseURLParams {
  baseUrl: string;
}

export interface MicroserviceAppSetAppBaseURLResponse {
  baseUrl: string;
  statusCode: number;
}

export interface MicroserviceAppGetIsAppReadyParams {}

export interface MicroserviceAppGetIsAppReadyResponse {
  isReady: boolean;
  statusCode: number;
}

export interface MicroserviceExtensionsDownloadParams {
  extensionFileName: string;
  projectName: string;
  url: string;
}

export interface MicroserviceExtensionsDownloadResponse {
  statusCode: number;
}

export interface ErrorResponse {
  code: number;
  description: string;
  name: string;
}

// `__params` and `__response` only exist at type level, to infer request/response types from a schema.
// A type alias (not an interface) keeps the implicit index signature of the JSON type it is intersected with.
export type TypedSchema<Params, Response> = {
  readonly __params?: Params;
  readonly __response?: Response;
};

export interface Schemas {
  readonly api: {
    readonly cloud: {
      readonly extensions: {
        readonly run: (typeof json)["api"]["cloud"]["extensions"]["run"] &
          TypedSchema<CloudExtensionsRunParams, CloudExtensionsRunResponse>;
      };
    };
    readonly local: {
      readonly app: {
        readonly run_viewer: (typeof json)["api"]["local"]["app"]["run_viewer"] &
          TypedSchema<LocalAppRunViewerParams, LocalAppRunViewerResponse>;
        readonly run_back: (typeof json)["api"]["local"]["app"]["run_back"] &
          TypedSchema<LocalAppRunBackParams, LocalAppRunBackResponse>;
        readonly project_folder_path: (typeof json)["api"]["local"]["app"]["project_folder_path"] &
          TypedSchema<LocalAppProjectFolderPathParams, LocalAppProjectFolderPathResponse>;
        readonly kill: (typeof json)["api"]["local"]["app"]["kill"] &
          TypedSchema<LocalAppKillParams, LocalAppKillResponse>;
      };
      readonly extensions: {
        readonly upload: (typeof json)["api"]["local"]["extensions"]["upload"] &
          TypedSchema<LocalExtensionsUploadParams, LocalExtensionsUploadResponse>;
        readonly run: (typeof json)["api"]["local"]["extensions"]["run"] &
          TypedSchema<LocalExtensionsRunParams, LocalExtensionsRunResponse>;
        readonly kill: (typeof json)["api"]["local"]["extensions"]["kill"] &
          TypedSchema<LocalExtensionsKillParams, LocalExtensionsKillResponse>;
      };
    };
    readonly microservice: {
      readonly app: {
        readonly set_viewer_base_url: (typeof json)["api"]["microservice"]["app"]["set_viewer_base_url"] &
          TypedSchema<
            MicroserviceAppSetViewerBaseURLParams,
            MicroserviceAppSetViewerBaseURLResponse
          >;
        readonly set_is_app_ready: (typeof json)["api"]["microservice"]["app"]["set_is_app_ready"] &
          TypedSchema<MicroserviceAppSetIsAppReadyParams, MicroserviceAppSetIsAppReadyResponse>;
        readonly set_back_base_url: (typeof json)["api"]["microservice"]["app"]["set_back_base_url"] &
          TypedSchema<MicroserviceAppSetBackBaseURLParams, MicroserviceAppSetBackBaseURLResponse>;
        readonly set_app_base_url: (typeof json)["api"]["microservice"]["app"]["set_app_base_url"] &
          TypedSchema<MicroserviceAppSetAppBaseURLParams, MicroserviceAppSetAppBaseURLResponse>;
        readonly get_is_app_ready: (typeof json)["api"]["microservice"]["app"]["get_is_app_ready"] &
          TypedSchema<MicroserviceAppGetIsAppReadyParams, MicroserviceAppGetIsAppReadyResponse>;
      };
      readonly extensions: {
        readonly download: (typeof json)["api"]["microservice"]["extensions"]["download"] &
          TypedSchema<MicroserviceExtensionsDownloadParams, MicroserviceExtensionsDownloadResponse>;
      };
    };
  };
}

declare const schemas: Schemas;
export default schemas;
