// Mesh
const POINTS_DEFAULTVISIBILITY = true;
const POINTS_DEFAULTSIZE = 10;
const POINTS_DEFAULTCOLOR = { red: 20, green: 20, blue: 20, alpha: 1 };
const EDGES_DEFAULTVISIBILITY = true;
const EDGES_DEFAULTWIDTH = 2;
const EDGES_DEFAULTCOLOR = { red: 20, green: 20, blue: 20, alpha: 1 };
const CELLS_DEFAULTVISIBILITY = true;
const CELLS_DEFAULTCOLOR = { red: 255, green: 255, blue: 255, alpha: 1 };
const POLYGONS_DEFAULTVISIBILITY = true;
const POLYGONS_DEFAULTCOLOR = { red: 255, green: 255, blue: 255, alpha: 1 };
const POLYHEDRA_DEFAULTVISIBILITY = true;
const POLYHEDRA_DEFAULTCOLOR = { red: 255, green: 255, blue: 255, alpha: 1 };

// Model
const CORNERS_DEFAULTVISIBILITY = true;
const CORNERS_DEFAULTCOLOR = { red: 20, green: 20, blue: 20, alpha: 1 };
const LINES_DEFAULTVISIBILITY = true;
const LINES_DEFAULTCOLOR = { red: 20, green: 20, blue: 20, alpha: 1 };
const SURFACES_DEFAULTVISIBILITY = true;
const SURFACES_DEFAULTCOLOR = { red: 255, green: 255, blue: 255, alpha: 1 };
const BLOCKS_DEFAULTVISIBILITY = true;
const BLOCKS_DEFAULTCOLOR = { red: 255, green: 255, blue: 255, alpha: 1 };

const MESH_COMPONENT_TYPES = ["Corner", "Line", "Surface", "Block"];

const DEFAULT_MODEL_COMPONENT_TYPE_COLORS = {
  Corner: CORNERS_DEFAULTCOLOR,
  Line: LINES_DEFAULTCOLOR,
  Surface: SURFACES_DEFAULTCOLOR,
  Block: BLOCKS_DEFAULTCOLOR,
};

export {
  POINTS_DEFAULTVISIBILITY,
  POINTS_DEFAULTSIZE,
  POINTS_DEFAULTCOLOR,
  EDGES_DEFAULTVISIBILITY,
  EDGES_DEFAULTWIDTH,
  EDGES_DEFAULTCOLOR,
  CELLS_DEFAULTVISIBILITY,
  CELLS_DEFAULTCOLOR,
  POLYGONS_DEFAULTVISIBILITY,
  POLYGONS_DEFAULTCOLOR,
  POLYHEDRA_DEFAULTVISIBILITY,
  POLYHEDRA_DEFAULTCOLOR,
  CORNERS_DEFAULTVISIBILITY,
  CORNERS_DEFAULTCOLOR,
  LINES_DEFAULTVISIBILITY,
  LINES_DEFAULTCOLOR,
  SURFACES_DEFAULTVISIBILITY,
  SURFACES_DEFAULTCOLOR,
  BLOCKS_DEFAULTVISIBILITY,
  BLOCKS_DEFAULTCOLOR,
  MESH_COMPONENT_TYPES,
  DEFAULT_MODEL_COMPONENT_TYPE_COLORS,
};
