const Status = {
  NOT_CREATED: "NOT_CREATED",
  CREATING: "CREATING",
  CREATED: "CREATED",
  NOT_CONNECTED: "NOT_CONNECTED",
  CONNECTING: "CONNECTING",
  CONNECTED: "CONNECTED",
}

export default Status
