name: Check branch origin

on:
  pull_request:

jobs:
  check-branch-protection:
    uses: Geode-solutions/actions/.github/workflows/branch-protection.yml@master
    with:
      branch_from: 'next'
      branch_to: 'master'
