name: CD

on:
  push:
    branches: [ master, next ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        python3 -m pip install --upgrade build
        python3 -m build
    - name: Upload
      run: |
        python3 -m pip install twine
        python3 -m twine upload --repository pypi dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }} 
