name: Test

on:
  push:
    branches-ignore:
      - master
      - next

jobs:
  test:
    uses: Geode-solutions/actions/.github/workflows/js-test.yml@master
    with:
      repos: ${{ vars.REPOS }}
      integration: true
      microservices_path: "tests/integration/microservices"
    secrets: inherit
