name: Test PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    uses: Geode-solutions/actions/.github/workflows/js-test-pr.yml@master
    with:
      repos: ${{ vars.REPOS }}
    secrets: inherit
