const RGB_MAX = 255;
const BACKGROUND_GREY_VALUE = 180;
const ACTOR_DARK_VALUE = 20;

const bgVal = BACKGROUND_GREY_VALUE / RGB_MAX;
const BACKGROUND_COLOR = [bgVal, bgVal, bgVal];
const actVal = ACTOR_DARK_VALUE / RGB_MAX;
const ACTOR_COLOR = [actVal, actVal, actVal];
const HOVER_THROTTLE_MS = 50;
const HOVER_TIMEOUT_MS = 500;
const WHEEL_TIME_OUT_MS = 600;

export {
  ACTOR_COLOR,
  BACKGROUND_COLOR,
  BACKGROUND_GREY_VALUE,
  HOVER_THROTTLE_MS,
  HOVER_TIMEOUT_MS,
  RGB_MAX,
  WHEEL_TIME_OUT_MS,
};
